# Generated by Django 5.1.6 on 2025-03-31 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('purchase_orders', '0003_alter_purchaseorder_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='locations.location'),
            preserve_default=False,
        ),
    ]
